### ISSUE TITLE
怎么编译成APP呢？

### ISSUE THREAD

**Issue by ilikeulinux** [Eanya-Tonic/CCTV_Viewer#1]

**Comment by Eanya-Tonic** [comment]
使用Android Studio即可，稍后会在release中发布编译好的apk文件

**Comment by ilikeulinux** [comment]
> 使用Android Studio即可，稍后会在release中发布编译好的apk文件

我刚刚把编译环境搭建好了，您那儿就有了好消息，再次感谢您
