### ISSUE TITLE
小米电视（安卓6.0.1），提示您当前的浏览器不支持视频播放

### ISSUE THREAD

**Issue by myvmiao** [Eanya-Tonic/CCTV_Viewer#10]
试了1.01.1 1.2 哪个版本都不行，提示让更换浏览器

**Comment by Eanya-Tonic** [comment]
您好，我在新版本中适配了本地x5内核，不知道能否解决您的问题

**Comment by myvmiao** [comment]
> 您好，我在新版本中适配了本地x5内核，不知道能否解决您的问题
已经解决了，但遥控器的右键选择频道建议再改进一下：https://github.com/Eanya-Tonic/CCTV_Viewer/issues/16

**Comment by Eanya-Tonic** [comment]
好的，我将会关闭这个issue，如果还有其他的问题和建议，欢迎提出
