### ISSUE TITLE
能否把设置放在外面？

### ISSUE THREAD

**Issue by wangdaodao** [Eanya-Tonic/CCTV_Viewer#105]
如题：https://github.com/Eanya-Tonic/CCTV_Viewer/issues/38

作者能否实现一下这个功能呢，有些盒子没有设置键，无法手动设置x5，能否把设置做的通用一些，谢谢

**Comment by Eanya-Tonic** [comment]
我下个版本在ok键那个换台界面底下加个设置按钮吧，免得打不开设置那个界面😂

**Comment by wangdaodao** [comment]
> 我下个版本在ok键那个换台界面底下加个设置按钮吧，免得打不开设置那个界面😂

感谢作者大大

**Comment by zbby1987** [comment]
> 我下个版本在ok键那个换台界面底下加个设置按钮吧，免得打不开设置那个界面😂

可以把央视频的中央台放在一级目录第三行，
设置的那些按钮放在后面几行。。。

**Comment by wangdaodao** [comment]
1.7.4版本我验证了下，已经解决了，谢谢作者

**Comment by zbby1987** [comment]
> 1.7.4版本我验证了下，已经解决了，谢谢作者

1.7.4啥时候出的？
