### ISSUE TITLE
可以出一个打包x5 64位内核的版本不

### ISSUE THREAD

**Issue by KioZhang** [Eanya-Tonic/CCTV_Viewer#106]
用的是n1盒子 是64位的系统 系统的webview又无法支持播放

**Comment by Eanya-Tonic** [comment]
64位x5内核在线获取已经在做适配了，n1盒子有root可以参考一下这个issue直接更新系统webview播放
https://github.com/Eanya-Tonic/CCTV_Viewer/issues/40

**Comment by KioZhang** [comment]
> 64位x5内核在线获取已经在做适配了，n1盒子有root可以参考一下这个issue直接更新系统webview播放 #40

多谢 更新一下了系统的webview就可以用了 下载至一下链接

https://github.com/Eanya-Tonic/CCTV_Viewer/issues/106#issuecomment-2421290318
