### ISSUE TITLE
1.7.3 x5 全屏播放底部闪屏厉害

### ISSUE THREAD

**Issue by Joyshub** [Eanya-Tonic/CCTV_Viewer#107]
全屏时候底部闪屏厉害，Android5.1 32bit

**Comment by Eanya-Tonic** [comment]
有没有截图 让我看下具体是哪里在闪？

**Comment by Joyshub** [comment]
[cctvviewer.zip](https://github.com/user-attachments/files/17483860/cctvviewer.zip)
看附件

**Comment by Eanya-Tonic** [comment]
看着有点像硬件加速引发的解码错误，央视网会不会闪屏呢？

**Comment by Joyshub** [comment]
会闪

**Comment by Joyshub** [comment]
有一半概率不闪，很奇怪，一半概率进去会闪

**Comment by Joyshub** [comment]
@Eanya-Tonic 可以解决吗

**Comment by Joyshub** [comment]
发给我试试

**Comment by Joyshub** [comment]
@Eanya-Tonic

**Comment by Joyshub** [comment]
把hardwareAccelerated改为false，没有画面，只有声音
