### ISSUE TITLE
播放一段时间后突然无网络

### ISSUE THREAD

**Issue by Eanya-Tonic** [Eanya-Tonic/CCTV_Viewer#112]
不知道是不是我的网络问题？会放着放着突然卡住无网络，然后再刷新也跳出来internet disconnect，再怎么刷新都不行了，重开app会恢复正常，但我用的是系统内核，也可能是系统内核的问题。

**Comment by zbby1987** [comment]
你可以用x5内核试试

**Comment by Eanya-Tonic** [comment]
发现是家里的网络有漫游重叠区，机顶盒正好在那里，过一会儿就漫游到另一个ap去了，是我的问题
