### ISSUE TITLE
遥控器菜单键功能冲突，无法生效

### ISSUE THREAD

**Issue by zbby1987** [Eanya-Tonic/CCTV_Viewer#12]
小米电视miui，长按菜单键会蹦出设置界面。
与目前app的设定冲突，导致无法生效！

**Comment by Eanya-Tonic** [comment]
不好意思，没用过miui，不知道还有这个快捷键，我会调整键位设置，抱歉

**Comment by Eanya-Tonic** [comment]
已经在新版本中将菜单键刷新触发调整为双击，避免快捷键冲突的问题，再次抱歉；我将会关闭这个issue，如果还有更多问题或建议，欢迎继续提出。
https://github.com/Eanya-Tonic/CCTV_Viewer/releases/latest
