### ISSUE TITLE
点菜单键，最好弹出选台列表，不要用方向键盲切台

### ISSUE THREAD

**Issue by zbby1987** [Eanya-Tonic/CCTV_Viewer#13]
一个一个切到中央13累不累啊

**Comment by Eanya-Tonic** [comment]
如果遥控器有数字键可以直接输入13，选台列表之后也会加入的

**Comment by Eanya-Tonic** [comment]
1.3版本更新中已经加入了选台列表功能，我将会关闭这个issue，如果你还有其他问题或建议，欢迎继续提出
https://github.com/Eanya-Tonic/CCTV_Viewer/releases/latest
