### ISSUE TITLE
安卓13安卓子系统x5内核加载失败

### ISSUE THREAD

**Issue by JackHanner** [Eanya-Tonic/CCTV_Viewer#14]
不知道我以前的一些iapp开发经验是否有用。以前我也做过x5内核加载的例子，是要启动是等待，一直检测x5内核是否架子成功的变量为true，如果没加载完直接使用浏览器控件之后是不会加载的，因此我觉得增加启动时间可能可以增加x5内核加载的成功率

**Comment by JackHanner** [comment]
1.3版本

**Comment by Eanya-Tonic** [comment]
安卓子系统可能无法加载x5内核，我这边的虚拟机由于是x86架构的都一直挂不上，实体机才能挂上x5内核；有部分实体机需要重启app才能加载内核，我想和您说的那个加载等待应该是同一个问题，我可以之后尝试加入首次启动的等待时间

**Comment by Eanya-Tonic** [comment]
Wsa由于用的是x86架构，x5内核挂不上去的（就和我的android studio虚拟环境差不多），因此这个问题目前解决不了。
