### ISSUE TITLE
切台之后视频会自动暂停

### ISSUE THREAD

**Issue by JackHanner** [Eanya-Tonic/CCTV_Viewer#15]
切台之后视频会自动暂停，每次切完台，等待加载完都要再按一下确认才能继续，希望切台加载成功后能自动模拟点击一下播放

**Comment by Eanya-Tonic** [comment]
1.3更新尝试解决这个bug，但是又产生了一些新bug，我已经再次在新的提交中再次尝试修复了；真的很尴尬，因为我手头上的机器都会自动播放，我很难排查问题的根源，抱歉

**Comment by JackHanner** [comment]
> 1.3更新尝试解决这个bug，但是又产生了一些新bug，我已经再次在新的提交中再次尝试修复了；真的很尴尬，因为我手头上的机器都会自动播放，我很难排查问题的根源，抱歉

现在我的电视也正常了，刚开始几次不行

**Comment by Eanya-Tonic** [comment]
> > 1.3更新尝试解决这个bug，但是又产生了一些新bug，我已经再次在新的提交中再次尝试修复了；真的很尴尬，因为我手头上的机器都会自动播放，我很难排查问题的根源，抱歉
> 
> 现在我的电视也正常了，刚开始几次不行

好的，非常高兴看到可以正常运行，我将会关闭这个issue，如果还有更多问题或建议欢迎随时提出
