### ISSUE TITLE
菜单键的【频道选择】建议增加记忆功能，不要每次都从上面往下按遥控器

### ISSUE THREAD

**Issue by myvmiao** [Eanya-Tonic/CCTV_Viewer#16]
菜单键的【选择频道】建议增加记忆功能，按遥控器的菜单键定位到当前所看的频道，而不是CCTV1的位置，再就是增加频道循环选择功能，比如我在CCTV1的位置，往上按遥控器就会到最底部的山东位置，或者在最底部的山东卫视往下按遥控器，跳回到CCTV1，可以大大提高效率。
除此外，能否增加鼠标操作支持，我有个N1的盒子没有遥控器，只能用鼠标，完全无法操作

**Comment by Eanya-Tonic** [comment]
记忆功能和循环菜单有道理，我之后可以进行相关的实现。
关于鼠标操控，我目前考虑的是滚轮换台，左右键打开菜单，我可以进行尝试，应该可以实现。

**Comment by Eanya-Tonic** [comment]
记忆功能和循环菜单，在大概1.5左右实现了，因此我想这个issue可以被关闭了，如您有其他问题，欢迎提出。
