### ISSUE TITLE
选台菜单，改成一二级目录形式的，

### ISSUE THREAD

**Issue by zbby1987** [Eanya-Tonic/CCTV_Viewer#19]
一级分为央视和地方，
二级列表建议做成三列，
(只有一列，往下找台按的次数太多，好累啊)
选台菜单位置放在左侧贴边比较合适，透明化处理，操作时不耽误看剧。
.
出菜单时，右侧同时显示出一些设置选项，比如自己调节清晰度。
据群里云南网友说，他们那播放超清720p感觉很卡，改成低一档的清晰度就不卡。。。自行改清晰度还是有需求的！

**Comment by Eanya-Tonic** [comment]
选台菜单，已改成一二级目录形式，感谢您的建议
