### ISSUE TITLE
先感谢作者辛苦编写这么好的APP，顺便提几个小小的建议。

### ISSUE THREAD

**Issue by ilikeulinux** [Eanya-Tonic/CCTV_Viewer#2]
退出APP的时候建议增加一个确认的步骤，比如连按两下返回键退出APP，或者按一下返回键就弹出是否退出的选择按钮。现在按一下就直接退出，家里老人看电视的时候容易误操作。

**Comment by Eanya-Tonic** [comment]
可以的，之后将做适配

**Comment by Eanya-Tonic** [comment]
[增加双击返回键退出逻辑](https://github.com/Eanya-Tonic/CCTV_Viewer/commit/dd881310e8c5e9f0813b434347a97f315f2278ef)
已做适配，将在其他调整之后重新编译apk

**Comment by Eanya-Tonic** [comment]
[v1.1](https://github.com/Eanya-Tonic/CCTV_Viewer/releases/tag/v1.1)
已更新并发布release
