### ISSUE TITLE
这样可以后台加载新切换的频道

### ISSUE THREAD

**Issue by zbby1987** [Eanya-Tonic/CCTV_Viewer#22]
前台给一个正在切换频道的提示，但依然播放当前台画面。
提示语可在屏幕正中(方便老人知道正在换台)，也可在屏幕右上角

后台加载成功后，前台自动关闭前一个标签页！

**Comment by Eanya-Tonic** [comment]
1.7已更新双标签缓冲换台，谢谢建议
