### ISSUE TITLE
不全屏显示【正在切换频道】的方法

### ISSUE THREAD

**Issue by zbby1987** [Eanya-Tonic/CCTV_Viewer#24]
把正在切换频道做成一个小一点的弹窗放在左下角。
用第二标签页后台打开新频道，
第二标签页视频成功全屏后，自动关闭前一个频道的标签页，秒切到新标签页。

是否可以实现？
这样可以用前一个频道的正常播放来代替  空等后一个频道时的黑屏白字。

**Comment by Eanya-Tonic** [comment]
多标签页理论上可以实现，理论上来说，多标签页好像是通过创建多个Webview对象甚至是一个Webview数组来实现的；这样确实可以实现切换的时候无感，不过换台很慢的问题估计还是会依旧存在。我可以进行尝试，但是对于低端设备可能还是需要保留单Webview切换的机制，避免占用过高。

**Comment by zbby1987** [comment]
> 多标签页理论上可以实现，理论上来说，多标签页好像是通过创建多个Webview对象甚至是一个Webview数组来实现的；这样确实可以实现切换的时候无感，不过换台很慢的问题估计还是会依旧存在。我可以进行尝试，但是对于低端设备可能还是需要保留单Webview切换的机制，避免占用过高。

要不设置里让他自行设置？
默认单标签页。。。
性能好的设备自己开启多标签页无感切台，但必须及时把前一个标签页占用的运存给释放掉

**Comment by Eanya-Tonic** [comment]
1.7已更新双标签页缓冲换台，不过出于提示，暂时保留正在切换频道的提示
