### ISSUE TITLE
小米盒子3S Android原生TV 6.0 无法通过音量键调整声音

### ISSUE THREAD

**Issue by Guancheng-Li** [Eanya-Tonic/CCTV_Viewer#42]
如题，使用的是1.50版带x5内核版本，应该是没有办法调用全局的音量控制。

**Comment by Guancheng-Li** [comment]
感谢大佬，设备可能比较小众，如果是设备相关问题，修的价值也许不大。

**Comment by Guancheng-Li** [comment]
> 同样问题+1， qq群里的网友，用的斐讯T1，也出现了同样问题： 打开软件时，遥控无法控制音量

有群吗？

**Comment by zbby1987** [comment]
> > 同样问题+1， qq群里的网友，用的斐讯T1，也出现了同样问题： 打开软件时，遥控无法控制音量
> 
> 有群吗？

刷机的群，不是这个软件的群
