### ISSUE TITLE
或许我有一个加快换台速度的思路

### ISSUE THREAD

**Issue by zbby1987** [Eanya-Tonic/CCTV_Viewer#43]
目前感知到的是网页加载速度慢，而不是视频加载响应速度慢。
这应该是网站本身杂七杂八的图片/超链内容多有关。
删了顶部导航栏，底部图片链接等杂七杂八的内容，不去加载应该就快的多了。
.
把这几个台的网页内容全下载到本地，
本地网页html文件改成只加载出网页里的播放器，其余顶部和底部各种导航/图片/超链都从本地页面代码里删了。
把这些本地文件保存在apk里，每次都只访问apk的本地网页，这个本地网页只和总站传输网页播放器&视频数据。
.
不知道这样，能不能通过央视网的加密加扰，实现正常播放。。。。

**Comment by zbby1987** [comment]
也可以通过类似油猴脚本的方法，直接屏蔽掉无关内容的加载

**Comment by matrix3d** [comment]
https://github.com/matrix3d/CCTV_Viewer/releases/tag/tagv23
此版本已删除图片加载

1. 使用 Webview 的 `WebViewClient` 类来控制加载。
2. 重写 `WebViewClient#shouldInterceptRequest()` 方法来拦截加载请求。
3. 检查请求的 URL，如果是要加载图像，则返回 `WebResourceResponse` 对象来阻止加载。
4. 在`WebResourceResponse` 对象中设置 `data` 属性为空，以防止加载图像。

```java
@Override
public WebResourceResponse shouldInterceptRequest(WebView view, WebResourceRequest request) {
    String url = request.getUrl().toString();
    if (url.endsWith(".png") || url.endsWith(".jpg") || url.endsWith(".jpeg")) {
        return new WebResourceResponse("image/gif", "UTF-8", new ByteArrayInputStream(new byte[0]));
    }
    return super.shouldInterceptRequest(view, request);
}
```

5. 也可以使用 `WebView#getSettings()` 方法来设置 `blockNetworkImage` 属性为 `true`，以阻止加载所有图像。

```java
WebView webView = (WebView) findViewById(R.id.webView);
WebSettings webSettings = webView.getSettings();
webSettings.setBlockNetworkImage(true);
```

**Comment by zbby1987** [comment]
> https://github.com/matrix3d/CCTV_Viewer/releases/tag/tagv23 此版本已删除图片加载
> 
> 1. 使用 Webview 的 `WebViewClient` 类来控制加载。
> 2. 重写 `WebViewClient#shouldInterceptRequest()` 方法来拦截加载请求。
> 3. 检查请求的 URL，如果是要加载图像，则返回 `WebResourceResponse` 对象来阻止加载。
> 4. 在`WebResourceResponse` 对象中设置 `data` 属性为空，以防止加载图像。
> 
> ```java
> @Override
> public WebResourceResponse shouldInterceptRequest(WebView view, WebResourceRequest request) {
>     String url = request.getUrl().toString();
>     if (url.endsWith(".png") || url.endsWith(".jpg") || url.endsWith(".jpeg")) {
>         return new WebResourceResponse("image/gif", "UTF-8", new ByteArrayInputStream(new byte[0]));
>     }
>     return super.shouldInterceptRequest(view, request);
> }
> ```
> 
> 5. 也可以使用 `WebView#getSettings()` 方法来设置 `blockNetworkImage` 属性为 `true`，以阻止加载所有图像。
> 
> ```java
> WebView webView = (WebView) findViewById(R.id.webView);
> WebSettings webSettings = webView.getSettings();
> webSettings.setBlockNetworkImage(true);
> ```

是不是可以考虑，把播放器和视频外的所有内容都给不加载？

**Comment by zbby1987** [comment]
经在手机上测试，
确实速度快了非常多！！！
在手机上长按屏幕，还会出现选台菜单。这样手机也能测了！
同时播放器底部控制栏里的全屏切换的按钮也消失不见了，无法看到屏蔽图片后的网页长什么样子。
.
另外，主版本加了体验优化的变动，希望分支版也能尽快加上。
比如
★能看到运行在哪个内核及其对应的版本号上！
★强制只使用x5且支持安卓4的版本，
★多行多列的选台列表 或 二级选台列表
★视频清晰度选择
.
明显的错误：
第1个中央一台明明是央视频，不是央视网！
第2个中央一台才是央视网！

**Comment by zbby1987** [comment]
> https://github.com/matrix3d/CCTV_Viewer/releases/tag/tagv23 此版本已删除图片加载
> 

这个版本里的第一个央视频的中央一，清晰度比较差，是因为用的540p来保证开机后的绝对流畅么？
其实可以考虑在设置里搞个720p和1080p的吧？

**Comment by zbby1987** [comment]
> https://github.com/matrix3d/CCTV_Viewer/releases/tag/tagv23 此版本已删除图片加载
> 
> 1. 使用 Webview 的 `WebViewClient` 类来控制加载。
> 2. 重写 `WebViewClient#shouldInterceptRequest()` 方法来拦截加载请求。
> 3. 检查请求的 URL，如果是要加载图像，则返回 `WebResourceResponse` 对象来阻止加载。
> 4. 在`WebResourceResponse` 对象中设置 `data` 属性为空，以防止加载图像。
> 
> ```java
> @Override
> public WebResourceResponse shouldInterceptRequest(WebView view, WebResourceRequest request) {
>     String url = request.getUrl().toString();
>     if (url.endsWith(".png") || url.endsWith(".jpg") || url.endsWith(".jpeg")) {
>         return new WebResourceResponse("image/gif", "UTF-8", new ByteArrayInputStream(new byte[0]));
>     }
>     return super.shouldInterceptRequest(view, request);
> }
> ```
> 
> 5. 也可以使用 `WebView#getSettings()` 方法来设置 `blockNetworkImage` 属性为 `true`，以阻止加载所有图像。
> 
> ```java
> WebView webView = (WebView) findViewById(R.id.webView);
> WebSettings webSettings = webView.getSettings();
> webSettings.setBlockNetworkImage(true);
> ```

@matrix3d @Eanya-Tonic 
我突然反应过来，你这就是浏览器里都能开启的无图模式啊。。。。
x5和webview肯定都是现成支持这个的！
在这个基础上，是不是还可以再屏蔽点东西去加速！？！？
