### ISSUE TITLE
建议：将频道信息改为通过配置文件读取

### ISSUE THREAD

**Issue by SinAxCosB** [Eanya-Tonic/CCTV_Viewer#44]
非常感谢您开发这样的程序，为家里的老人收看电视提供了相当的便利。
我想提出一个建议，希望能够改善项目的使用体验。

当前，频道URL信息是写死在程序中的，如果将这些信息移到配置文件中读取会更加灵活和方便，并可以带来如下好处：
用户自定义频道：对于一些特定的情况，比如老年人需要观看方言频道，可以编辑配置文件自行添加频道，从而满足个性化的观看需求。
简化更新流程：如果频道URL发生变更，只需更新配置文件即可，而不需要重新编译程序，可以简化维护和更新的流程。

再次感谢您为电视适老化做出的贡献。

**Comment by zbby1987** [comment]
想到一起去了

**Comment by SinAxCosB** [comment]
如今可以通过github action进行软件编译，大家都可以自己修改需要的节目列表了。
感谢作者的适配。
