### ISSUE TITLE
sony电视上的不正常

### ISSUE THREAD

**Issue by loratadinetables** [Eanya-Tonic/CCTV_Viewer#5]
1、图标显示不正常，CCTV只能看到半个cct。
2、要按一点确定，才能播放。

**Comment by Eanya-Tonic** [comment]
暂停逻辑我之后会想办法修复，因为之前适配x5内核的时候把代码逻辑改乱了，导致错误的暂停

图标问题我猜测可能是leanback图标尺寸问题，我需要再研究一下

**Comment by loratadinetables** [comment]
1.4已解决。
