### ISSUE TITLE
待优化：软件启动时的白屏晃眼，可加一个转圈的loading过场动画或者小体积启动图 (群友反馈)

### ISSUE THREAD

**Issue by zbby1987** [Eanya-Tonic/CCTV_Viewer#53]
开启软件时，加个小体积的图片，或者一个蒙版。

不至于纯白色晃眼睛。

浏览器可以默认是暗夜模式，
(或者视频全屏前加个灰色透明度蒙版，全屏播放后再消失),

打开央视频这种纯白色背景的网站时，不至于被网站背景晃眼

**Comment by Eanya-Tonic** [comment]
开屏已调整为灰色，避免伤眼
