### ISSUE TITLE
怎么用遥控器启动x5内核呀？

### ISSUE THREAD

**Issue by tedcriss** [Eanya-Tonic/CCTV_Viewer#54]

**Comment by tedcriss** [comment]
目前没有发现稳定的复现方法，就是疯狂关了再开，好像十次不到就会切换到x5。

**Comment by turingking** [comment]
https://github.com/turingking/CCTV_Viewer/releases/tag/v1.0
增加了手动开启的入口，需要鼠标配合操作

**Comment by tedcriss** [comment]
> https://github.com/turingking/CCTV_Viewer/releases/tag/v1.1
> 增加了手动开启的入口

牛逼🥳🥳
