### ISSUE TITLE
版本放置错误

### ISSUE THREAD

**Issue by JackHanner** [Eanya-Tonic/CCTV_Viewer#6]
之前我还以为x5内核没有成功加载，原来我下的是1.0，但是你却把它放在1.2的发行里面了

**Comment by Eanya-Tonic** [comment]
1.0版本没有适配x5内核，不好意思，可以参考github release的latest标签选择最新版本下载

**Comment by Eanya-Tonic** [comment]
这是github release的最新版本下载链接：https://github.com/Eanya-Tonic/CCTV_Viewer/releases/latest
希望这能解决你的问题，抱歉带来的困扰，我将会关闭这个issue，如果还有别的问题或建议，欢迎再次提出
