### ISSUE TITLE
看地方台进入央视频网址的时候隐私弹窗无法选择确定

### ISSUE THREAD

**Issue by ArvineKwok** [Eanya-Tonic/CCTV_Viewer#71]
您好，我是索尼电视，请问看地方台时进入央视频网站应该如何正确关闭隐私弹窗？
两个版本的app都在进入网站后尝试按遥控器的确认键，均没有反应

**Comment by zkitefly** [comment]
> 您好，我是索尼电视，请问看地方台时进入央视频网站应该如何正确关闭隐私弹窗？
> 两个版本的app都在进入网站后尝试按遥控器的确认键，均没有反应

使用 v1.6.1 看看？

还不行截个图

**Comment by ArvineKwok** [comment]
> > 您好，我是索尼电视，请问看地方台时进入央视频网站应该如何正确关闭隐私弹窗？
> > 两个版本的app都在进入网站后尝试按遥控器的确认键，均没有反应
> 
> 使用 v1.6.1 看看？
> 
> 还不行截个图

谢谢，我试一下！

**Comment by ArvineKwok** [comment]
地方台可以播放了，谢谢！
