### ISSUE TITLE
这里的字体可以大一些吗

### ISSUE THREAD

**Issue by xiaoxin6182** [Eanya-Tonic/CCTV_Viewer#86]
这里的字体可以大一些吗，老年人看不清

![PixPin_2024-08-15_09-17-11](https://github.com/user-attachments/assets/c257b460-88f7-439b-b869-5f8e82ed0c95)

**Comment by Eanya-Tonic** [comment]
这里的字体应该没这么小啊，请问这是多少分辨率的电视机？

**Comment by zbby1987** [comment]
我65寸电视，差不多也是这么大，
我家电视之前能用，现在打开这个app反而会白屏/闪退

**Comment by Eanya-Tonic** [comment]
[换台抽屉字体增大](https://github.com/Eanya-Tonic/CCTV_Viewer/commit/45a70eecbac5daf487af23f756dcb7f830adc889)
已经尝试调大字体 请等待下一版本发布

**Comment by zbby1987** [comment]
其实不如直接给基于v1.4的matrix分支版加一个刚刚修复后的x5内核试试效果。
字体大小，不如放在设置里让用户自己调节，或者在选台界面底部加个字体一级菜单按钮，点进去后出二级菜单，里面是+和-(或者10 11 12 13等字号)(或者特小&nbsp; 小&nbsp; 中&nbsp; 大&nbsp; 特大)。



---原始邮件---


 
换台抽屉字体增大
 已经尝试调大字体 请等待下一版本发布

**Comment by Eanya-Tonic** [comment]
https://github.com/Eanya-Tonic/CCTV_Viewer/releases/latest
新版本已在设置菜单增加自定义字体大小
